template: |
  ## What’s Changed
  $CHANGES

changelog:
  exclude:
    labels:
      - "ignore for release ✂️"
  categories:
  - title: ☄️ Breaking Changes
    labels:
      - "breaking change ☄️"
  - title: 🎉 New Features 
    labels:
      - "enhancement 💎"
  - title: 🐛 Bug Fixes
    labels:
      - "bug 🐛"
  - title: 🧰 Maintenance
    labels: 
      - "chore 🧹"
      - "dependencies 🛠"
  - title: 📓 Documentation
    labels: 
      - "documentation 📓"
  - title: 🃏 Miscellaneous
    labels:
      - "*"