version: '2'
services:
  spring-project:
    image: spring-project:latest
    container_name: spring-project
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spring-project
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:12
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring-project
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432 
volumes:
  pgdata:
