{
 "title": "Vivo -  AWS EKS Gateway/Vivo Easy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "EKS Gateway/Vivo Easy  - Ec2 Instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "eks-34baa882-9f7b-1365-bd6e-142b4dd0abf0"
     },
     "metricName": "GroupDesiredCapacity",
     "namespace": "AWS/AutoScaling",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EKS - Vivo Easy/Gateway - CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "eks-34baa882-9f7b-1365-bd6e-142b4dd0abf0"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EKS - Vivo Easy/Gateway - Net-In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "eks-34baa882-9f7b-1365-bd6e-142b4dd0abf0"
     },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "EKS - Vivo Easy/Gateway - Net Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "AutoScalingGroupName": "eks-34baa882-9f7b-1365-bd6e-142b4dd0abf0"
     },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}