{
 "title": "Vivo - EC2 Available",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vivo - Check Status - vivo-ipsec02",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-01f4e8f34bfabe216" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Vivo - Check Status - vivo-ipsec03",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0c62ea4e0be19fdeb" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Vivo - Check Status - vivo-ipsec01",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0cf192b0613046d12" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Vivo - Check Status - vivo-couchbase01",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-01d2a491435b3788a" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Vivo - Check Status - vivo-couchbase02",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-008f3d8e4f8ce57fc" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Vivo - Check Status - vivo-couchbase03",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0601c5f3a0c5e359d" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Vivo - EBS - Burst Balance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "VolumeId": "*" },
     "metricName": "BurstBalance",
     "namespace": "AWS/EBS",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Vivo - EC2 - CPU Consume",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Vivo - Burst Volume - EBS VPNs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "VolumeId": "*" },
     "metricName": "BurstBalance",
     "namespace": "AWS/EBS",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Vivo - CPU Consume - VPNs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}