{
 "title": "RDS - Vivo Easy",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "RDS - Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS - FreeStorageSpace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS - FreeAbleMemory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS - WriteThroughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RDS - ReadThroughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "*" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "sa-east-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}