apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: db-applications
  namespace: prod
spec:
  backendType: secretsManager
  dataFrom:
  - secret-applications
  region: sa-east-1
