name: CI - Terraform provision 

on:
  workflow_dispatch:
  # pull_request:
  #   paths-ignore:
  #     - '*.md'
  #     - 'terraform/terraform-sample-eks/docs/**'
  #     - 'terraform/terraform-sample-eks/*.md'
  #     - 'serverless/'
  #     - k8s-and-helms/
  #     - 'gitops/'
  #     - 'docker/'
  #     - 'cloudformation/'
  #     - 'ci-cd/'
  #     - 'automation-commons/'

  # push:
  #   paths-ignore:
  #     - '*.md'
  #     - 'terraform/terraform-sample-eks/docs/**'
  #     - 'terraform/terraform-sample-eks/*.md'
  #     - 'serverless/'
  #     - k8s-and-helms/
  #     - 'gitops/'
  #     - 'docker/'
  #     - 'cloudformation/'
  #     - 'ci-cd/'
  #     - 'automation-commons/'
  #   branches:
  #     - main
  #     - release-*
  # schedule:
  #   - cron: "0 11 * * 1-5"
jobs:
  lint:
    name: Linting
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Init cluster'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform/terraform-sample-eks/examples/cluster'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
      - name: 'Terraform Validate cluster'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: 'terraform/terraform-sample-eks/examples/cluster'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cluster-test:
    name: Test cluster module
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
      - name: 'Terratest'
        uses: ./.github/terratest
        with:
          args: "-run TestTerraformAwsEksCluster"
